# This is an example OpenEMPIRE configuration file. 
# To be used with the execution script OpenEMPIRE/run.py

USE_TEMP_DIR : True #
temp_dir : '/mnt/beegfs/users/shamimh'
version : 'europe_v52'
versionp : 'europe_v52_base'
Horizon : 2060
NoOfScenarios : 5
lengthRegSeason : 168
discountrate : 0.05
WACC : 0.05
solver : "Gurobi" #"CPLEX" #  #"Xpress" #
scenariogeneration : False
fix_sample : True
EMISSION_CAP : True #False
IAMC_PRINT : False #True
WRITE_LP : False #True
PICKLE_INSTANCE : False #True 
